version: "3"
services:

  server:
    image: node:latest
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: npm run server
    env_file: .env.local
    environment:
      NODE_ENV: production
      PGUSER: postgres
      PGHOST: db
      PGPASSWORD: postgres
      PGDATABASE: intl
      PGPORT: 5432
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: "postgres:9.6"
    volumes:
      - ./psql/:/docker-entrypoint-initdb.d/
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  dev-server:
    image: node:latest
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/true
    # command: npm run build # uncomment this line to use this container for the build
    # command: npm run start # uncomment this line to start the development server on the own port
    env_file: .env.local
    environment: 
      NODE_ENV: development
    ports:
      - 3001:3000
