const prefix = 'ADDMODULE/'

const ADD_MODULE_REQUEST = prefix + 'ADD_MODULE_REQUEST'
const ADD_MODULE_SUCCESS = prefix + 'ADD_MODULE_SUCCESS'
const ADD_MODULE_FAILURE = prefix + 'ADD_MODULE_FAILURE'

const CLEAR_MODULE_NAME = prefix + 'CLEAR_MODULE_NAME'
const TYPE_MODULE_NAME = prefix + 'TYPE_MODULE_NAME'

export {
  ADD_MODULE_REQUEST,
  ADD_MODULE_SUCCESS,
  ADD_MODULE_FAILURE,
  CLEAR_MODULE_NAME,
  TYPE_MODULE_NAME
}
