const prefix = 'MODULES/'

const LOAD_DICTIONARY_REQUEST = prefix + 'LOAD_DICTIONARY_REQUEST'
const LOAD_DICTIONARY_SUCCESS = prefix + 'LOAD_DICTIONARY_SUCCESS'
const LOAD_DICTIONARY_FAILURE = prefix + 'LOAD_DICTIONARY_FAILURE'

const LOAD_ALL_DICTIONARIES_REQUEST = prefix + 'LOAD_ALL_DICTIONARIES_REQUEST'
const LOAD_ALL_DICTIONARIES_SUCCESS = prefix + 'LOAD_ALL_DICTIONARIES_SUCCESS'
const LOAD_ALL_DICTIONARIES_FAILURE = prefix + 'LOAD_ALL_DICTIONARIES_FAILURE'

export {
  LOAD_DICTIONARY_REQUEST,
  LOAD_DICTIONARY_SUCCESS,
  LOAD_DICTIONARY_FAILURE,
  LOAD_ALL_DICTIONARIES_REQUEST,
  LOAD_ALL_DICTIONARIES_SUCCESS,
  LOAD_ALL_DICTIONARIES_FAILURE
}
